deploy:
  provider: npm
  email: glfabry2@illinois.edu
  api_key:
    secure: Htnk4CmZ3HDoqf96tRJ/Lsa6l8kido20jZ9e/MQneVNKmsUspthS/X3KbqEWV7ZJUIPkizfOe7K4K3GrkkchSUM5s4XABz/A4t65Asd+o55D1v383bNXXzbs+Fh4QKe1o3ar6TyIN2VkY+1hDiNIShAf8hdfDceKgJ2ihLmqawwvmcWmcaadd9y+cJsJUpbenlO8uLGo8mAxUFmDUP9aQB31e0fbibB8AiTOmNpRt6jj1t2wOVaTvJv+KWB1ZwPVy2UF0KFDpHYnw3lNJmm8vg8IzVnhfGCppSAUL97X40bgG8fZ+EI+mm5YBs1HLP5WqKq5n01LGAhRVstAM1sRKRhJBOWguA3sw3tIEtgFXXkbSe+U9ZNxKJm9RYx52yRgOpYy2ca3X+ogLdrPWseu9FpOfsX2fhRIuZOwv+nk/Fago2PK01uZ2/d985lF8tNKM/mD9bU8SFQFY0buV5NecRZtsBI13KTaOjbvdViqZHTagO91Vy9V1ZVNy03EK2dd8AAohKeFmy3hYmmsDzh72ro8QVKrQxqttSDBlzVtgeo4s6qDF8hhVlNbbTjCsydvS5AMokpeK9XQEO5iIwTlPoTrmuzne4OYyu0FaH6JMSYxp7NakZyd4DjWbUjwRh08H4rUQiCN3qq/MCy3joU6MmL96PlnUU7IIm35BnfLYTM=
  on:
    branch: master
